{% set version = "1.0" %}

package:
  name: mkdocs-bootswatch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs-bootswatch/mkdocs-bootswatch-{{ version }}.tar.gz
  sha256: 6be56764675814036a507d32828710e93dbe3e7aced2cdd820b946a3ebf2308e

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mkdocs_bootswatch
    - mkdocs_bootswatch.amelia
    - mkdocs_bootswatch.cerulean
    - mkdocs_bootswatch.cosmo
    - mkdocs_bootswatch.cyborg
    - mkdocs_bootswatch.flatly
    - mkdocs_bootswatch.journal
    - mkdocs_bootswatch.readable
    - mkdocs_bootswatch.simplex
    - mkdocs_bootswatch.slate
    - mkdocs_bootswatch.spacelab
    - mkdocs_bootswatch.united
    - mkdocs_bootswatch.yeti

about:
  home: http://www.mkdocs.org
  license: BSD 2-Clause
  summary: 'Bootswatch themes for MkDocs'

extra:
  recipe-maintainers:
    - ocefpaf
