travis:
  secure:
    BINSTAR_TOKEN: o7XOERDwaM3vSBsPKptFjLT3a4IY7UFKf+mck46m32SCv2/fIwOp9jAYc/pnejPSHrMRe/YxhsHxUdadTL/M8QX24woslmOV2tOou4C63pVUKomFL4h8cX/eU0031Hrc55twEZ54bSBjSlaapc3+K3UqJW6lV/4v0qcg4r9NqhHkLyK547IUX3upDnW6wLOVOtN9SVxze+HRDV6MQSFJ9Rns6l4mYpgDeNFsngJ5Ce6Q6UQciYrWSKx4XOQMpykJUOKHKM63tszhjGU9xbm7n+3slZj/ND5oaBQLIELqHSztvsRaI0a5JLAJVAcfpjI2ISaKFWqQ9++uCNEIxwnZWYJMsoUR4os3Q7ZjvmZ4bXSXxtiPd2ULtGKILA0sPDYquY+lG/VIUkcfisLrnLGuOYamdq+aptYhTNWHBYiY6Tp4H5sQrXny8IFQPX6BNHpaqmKv35tEeU3s6FOQ1JWSSuD7hjMZRxWdPe8h/NVA3Pl1jEP9t0Qa6JtDlmt7UXLps4tbcmtvZc+30Zh8c+Dn8n8SdJvyDU0El0W2+EOkyVB4bQ4XBzwYwKwZFlwbZZy6XIPKRd5c8pdhD41ZPA9ZD9NyOtTOlRm4TNkZmiydR4KOsroWQoh0uxwo33jzkb+vdM6lLvP9IAclmR6UiFr73WRh7GxPwSGaWK+4xRv6Z1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
